services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Dan\Jobfair\:
    resource: '../Classes/*'

  Dan\Jobfair\Domain\Validator\ApplicationCreateValidator:
    public: true
    shared: false

  Dan\Jobfair\Property\TypeConverter\UploadedFileReferenceConverter:
    tags:
      - name: extbase.type_converter
        priority: 30
        target: TYPO3\CMS\Extbase\Domain\Model\FileReference
        sources: array

  Dan\Jobfair\Property\TypeConverter\ObjectStorageConverter:
    tags:
      - name: extbase.type_converter
        priority: 20
        target: TYPO3\CMS\Extbase\Persistence\ObjectStorage
        sources: array
