services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Dan\Jobfair\:
    resource: '../Classes/*'

  Dan\Jobfair\Domain\Validator\ApplicationCreateValidator:
    public: true
    shared: false
